# ex: set ro:
# DO NOT EDIT THIS FILE
# Generated by Parrot::Configure::Compiler from build/Makefile.in

PRODUCT_NAME  = libxml

## arguments we want to run parrot with
PARROT_ARGS   =

## configuration settings
VERSION       = /3.3.0-devel
BIN_DIR       = /Users/uasi/Dev/Projects/rakudo/parrot_install/bin
LIB_DIR       = /Users/uasi/Dev/Projects/rakudo/parrot_install/lib$(VERSION)
DOC_DIR       = /Users/uasi/Dev/Projects/rakudo/parrot_install/share/doc$(VERSION)
MANDIR        = /Users/uasi/Dev/Projects/rakudo/parrot_install/man$(VERSION)

# Set up extensions
LOAD_EXT      = .bundle
O             = .o

# Various paths
PERL6GRAMMAR  = $(LIB_DIR)/library/PGE/Perl6Grammar.pbc
NQP           = $(LIB_DIR)/languages/nqp/nqp.pbc
PCT           = $(LIB_DIR)/library/PCT.pbc
PMC_DIR       = src/pmc

## Setup some commands
MAKE          = +make -C
PERL          = perl
CAT           = $(PERL) -MExtUtils::Command -e cat
CHMOD         = $(PERL) -MExtUtils::Command -e chmod
CP            = $(PERL) -MExtUtils::Command -e cp
MKPATH        = $(PERL) -MExtUtils::Command -e mkpath
RM_F          = $(PERL) -MExtUtils::Command -e rm_f
RM_RF         = $(PERL) -MExtUtils::Command -e rm_rf
POD2MAN       = pod2man
PARROT        = $(BIN_DIR)/parrot
PBC_TO_EXE    = $(BIN_DIR)/pbc_to_exe

# MACOSX_DEPLOYMENT_TARGET must be defined for OS X compilation/linking
export MACOSX_DEPLOYMENT_TARGET = 10.6
PROVE         = prove
PERL6         = perl6

DYNPMC_GROUP  = $(PMC_DIR)/$(PRODUCT_NAME)_group$(LOAD_EXT)

PMC_DEPS = \
	build/src/pmc/Makefile.in \
	src/pmc/*.pmc

DOCS = README

BUILD_CLEANUPS = \
	"src/gen_*.pir" \
	"*.c" \
	"*$(O)" 

TEST_CLEANUPS =

# the default target
build: \
	$(DYNPMC_GROUP) 

$(DYNPMC_GROUP): $(PMC_DEPS)
	$(MAKE) $(PMC_DIR)

all: build 

Makefile: build/Makefile.in
	$(PERL) Configure.pl

# This is a listing of all targets, that are meant to be called by users
help:
	##! Listing

test-parrot: build
	$(PROVE) --exec=$(PARROT) t/parrot -v

test-perl6: build
	PERL6LIB=lib $(PROVE) --exec=perl6 t/perl6 -v

test: test-parrot test-perl6

testclean:
	$(RM_F) $(TEST_CLEANUPS)

clean:
	$(MAKE) $(PMC_DIR) clean
	$(RM_F) $(TEST_CLEANUPS) $(BUILD_CLEANUPS)

realclean:
	$(MAKE) $(PMC_DIR) realclean
	$(RM_F) $(TEST_CLEANUPS) $(BUILD_CLEANUPS) Makefile

distclean: realclean

# Local variables:
#   mode: makefile
# End:
# vim: ft=make:

